#!/usr/bin/env perl
use v5.12;
use lib 'lib';
use WireRoom::Message;
use Git::Hook::PostReceive;
use HTTP::Request::Common;
use JSON;
use YAML;

my $config = YAML::LoadFile "config/testing.yml";
my $baseUrl = "http://" . $config->{Host};
$baseUrl .= ":" . $config->{Port} if $config->{Port} && $config->{Port} != 80;

my @names = qw(foo bar zoo);

my $cnt = shift || 10;
say "Posting commit log to " , $cnt;
for ( 1..$cnt ) {
    my $rand = int(rand(20)) + 1;
    my $payload = Git::Hook::PostReceive->new->run( 
        'HEAD',
        'HEAD~' . $rand,
        'refs/heads/master'
    );
    $payload->{user} = $names[ int rand 3 ];
    my $msg = WireRoom::Message->new( 
        type    => 'notification.git',
        payload => $payload,
        room    => "Hall"
    );
    $msg->submit( url => "$baseUrl/=/git/Hall" );
}
