#!/bin/bash

# re-compress javascripts
bash scripts/compress
git status | grep wireroom.min && (
    git commit -a -m "Recompress javascript"
)
git push origin master

# update remote server
ssh git.corneltek.com "cd /home/wireroom/WireRoom; git pull --rebase origin master; " \
            " git push origin master ; " && git pull --rebase origin master
